server: 
  port: 8000
  servlet:
    context-path: /estoque
spring:
  application:
    name: estoque
  profiles:
    active:
    - test

    
  rabbitmq:
    connection-timeout: 5000
    host: localhost
    port: 5672
    username: nando.systempro@hotmail.com
    password: Fe2812
        
    