server:
  port: 9000
  servlet:
    context-path: /sales
spring:
  application:
    name: sales
  profiles:
    active:
    - test

    
  rabbitmq:
    host: localhost
    port: 5672
    username: nando.systempro@hotmail.com
    password: Fe2812
        

    
 


    